# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Med Track CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,18.x,20.x]

    steps:
    - uses: actions/checkout@v3

    # - name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #   node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    #   cache-dependency-path: med-tracker/package-lock.json

    - name: Print npm version
      run: npm --version

    - name: Print node version
      run: node --version

    - name: Check file structure
      run: ls -alh
    
    - name: Clear NPM cache forcefully
      run: npm cache clean --force

    - name: Remove node_modules directory
      run: rm -rf node_modules
      
    - name: Install Dependencies
      run: npm ci --force

    - name: Build
      run: npm run build --if-present

   # - name: Run Tests
    #  run: npm test
    # working-directory: med-tracker


